const DEVELOPERS = new Map([
  ["", "10betterpages GmbH"],
  ["", "115.com"],
  ["", "2345.com"],
  ["", "8pecxstudios"],
  ["", "A6 Corp"],
  ["", "abonti.com"],
  ["", "Access"],
  ["", "AdaptiveBee SASU"],
  ["", "adbeat.com"],
  ["", "AddThis.com"],
  ["", "Adobe Systems Incorporated"],
  ["", "adscanner.tv"],
  ["", "AgileBits, Inc."],
  ["", "Ahrefs Pte Ltd"],
  ["", "AirWatch LLC"],
  ["", "Alexa Internet, Inc"],
  ["", "Alexander Clauss"],
  ["", "Aliaksandr Valialkin"],
  ["", "Alibaba"],
  ["", "Aloha Mobile Ltd"],
  ["", "alphaseobot.com"],
  ["", "Amazon.com, Inc."],
  ["", "America Online, Inc."],
  ["", "Anderson Che"],
  ["", "Andrew Horton"],
  ["", "AOL"],
  ["", "Apple Inc"],
  ["", "APUS-Group"],
  ["", "archive.org"],
  ["", "ArchiveTeam"],
  ["", "Ask.com"],
  ["", "Atsushi Jike"],
  ["", "Automattic"],
  ["", "Avant Force"],
  ["", "AVAST Software s.r.o."],
  ["", "Avira Operations GmbH & Co. KG."],
  ["", "Axandra GmbH"],
  ["", "Baidu"],
  ["", "Beamrise Team"],
  ["", "begun.ru"],
  ["", "Blackboard Inc."],
  ["", "Blekko Inc."],
  ["", "Blizzard Entertainment Inc"],
  ["", "bloglovin.com"],
  ["", "Bloop S.R.L."],
  ["", "Blue Link Labs"],
  ["", "BoardReader"],
  ["", "BrandVerity"],
  ["", "BRAVO UNICORN PTE LTD"],
  ["", "browsershots.org"],
  ["", "browzar.com"],
  ["", "Callpod Inc."],
  ["", "Cameron Kaiser"],
  ["", "capture.heartrails.com"],
  ["", "Catchpoint Systems, Inc."],
  ["", "Cent Studio"],
  ["", "CheckMark Network"],
  ["", "checksite.us"],
  ["", "Chedot.com"],
  ["", "Cheetah Mobile"],
  ["", "Christian Dywan"],
  ["", "Christian Noon"],
  ["", "Clickagy"],
  ["", "Cloud System Networks"],
  ["", "CloudFlare, Inc."],
  ["", "CloudMosa Inc."],
  ["", "Coc Coc Company Limited"],
  ["", "CommonCrawl Foundation"],
  ["", "Comodo Group Inc"],
  ["", "Compuware Corporation"],
  ["", "comScore, Inc."],
  ["", "Core Inc"],
  ["", "Corey Donohoe"],
  ["", "CrazyBrowser.com"],
  ["", "crazywebcrawler.com"],
  ["", "cstking"],
  ["", "Cxense ASA"],
  ["", "DareBoost"],
  ["", "Dassault Systemes"],
  ["", "Datagnion GmbH"],
  ["", "datasift.com"],
  ["", "Daum Communications Corp"],
  ["", "David Frank"],
  ["", "David Rosca and Community"],
  ["", "Deepnet Security"],
  ["", "Diigo, Inc."],
  ["", "Discord"],
  ["", "DocBase"],
  ["", "DomainSigma"],
  ["", "DomainSONO"],
  ["", "Domainstats International AB"],
  ["", "DomainTools"],
  ["", "Dr. Manfred Schauer"],
  ["", "DuckDuckGo"],
  ["", "easou.com"],
  ["", "Easy-Thumb.net"],
  ["", "Echobox Limited"],
  ["", "Elbert Alias"],
  ["", "elefent.eu"],
  ["", "Element Software"],
  ["", "embed.ly"],
  ["", "Entireweb Sweden AB"],
  ["", "Ericsson Research"],
  ["", "eVenture Capital Partners II, LLC"],
  ["", "Evernote Corporation"],
  ["", "everyfeed.com"],
  ["", "eXenSa"],
  ["", "Experian Ltd"],
  ["", "Fabien Coeurjoly"],
  ["", "Facebook"],
  ["", "FCCN"],
  ["", "feedly.com"],
  ["", "Fenrir Inc"],
  ["", "FlashPeak Inc"],
  ["", "Flipboard, Inc."],
  ["", "FREE SAS"],
  ["", "Free Software Foundation, Inc."],
  ["", "gadu-gadu.pl"],
  ["", "Genieo"],
  ["", "Geometry OU"],
  ["", "GESKIMO SRL"],
  ["", "getintent.com"],
  ["", "gigablast.com"],
  ["", "Github"],
  ["", "Google Inc"],
  ["", "Gordon Lyon"],
  ["", "Grammarly Inc."],
  ["", "Grapeshot Limited"],
  ["", "Greg Lindahl"],
  ["", "GroupHigh LLC"],
  ["", "GTmetrix"],
  ["", "Guangzhou Network"],
  ["", "Handspring"],
  ["", "Hans Hasselberg"],
  ["", "Hatena Co., Ltd."],
  ["", "Headbanging Sasquatches"],
  ["", "Heartlass, Inc."],
  ["", "HiQPdf Software"],
  ["", "HJ van Rantwijk"],
  ["", "HP"],
  ["", "HTC"],
  ["", "http://law.di.unimi.it"],
  ["", "Huawei"],
  ["", "HubPages Inc."],
  ["", "HubSpot, Inc."],
  ["", "Hytto Ltd."],
  ["", "IBM"],
  ["", "Ichiro"],
  ["", "Idee Inc."],
  ["", "iLegendSoft, Inc."],
  ["", "Imagine Easy Solutions, LLC"],
  ["", "Impact Tech, Inc"],
  ["", "infegy.com"],
  ["", "Installatron LLC."],
  ["", "Integral Ad Science, Inc"],
  ["", "Intel Corporation"],
  ["", "Iridium Browser Team"],
  ["", "Itteco"],
  ["", "Jaime Iniesta"],
  ["", "James Hurst"],
  ["", "Jaohawi AB"],
  ["", "Jeanfrancois Arcand"],
  ["", "Jobboerse.com"],
  ["", "Jolla Ltd."],
  ["", "Jonas Genannt (HggH)"],
  ["", "Kakao Corp"],
  ["", "Kawe Apps"],
  ["", "Kaylon Technologies"],
  ["", "KDE e.V."],
  ["", "Keanu Lee"],
  ["", "Kerverus IT Ltd"],
  ["", "Kingsoft"],
  ["", "kinza.jp"],
  ["", "Kitsuregawa Laboratory, The University of Tokyo"],
  ["", "KKBOX Taiwan Co., Ltd."],
  ["", "kmeleonbrowser.org"],
  ["", "Komodia Inc"],
  ["", "Kuaiso Beijing ICP"],
  ["", "Laurent Jouanneau"],
  ["", "Leiki Ltd"],
  ["", "Let's Encrypt"],
  ["", "LetSearch.ru"],
  ["", "LG"],
  ["", "Lightspeed Systems"],
  ["", "Linden Labs"],
  ["", "Line Corporation"],
  ["", "Linkdex Limited"],
  ["", "LinkedIn Corporation"],
  ["", "Linkfluence SAS"],
  ["", "Linkis.com"],
  ["", "LinkPad"],
  ["", "Linux Foundation"],
  ["", "LogicWare & LSoft Technologies"],
  ["", "LongURL.org"],
  ["", "ltx71.com"],
  ["", "Lucas Ou-Yang"],
  ["", "Lucidworks"],
  ["", "Lunascape Corporation"],
  ["", "Mail.Ru Group"],
  ["", "Majestic-12 Ltd"],
  ["", "Makoto Kinoshita"],
  ["", "Maple Studio"],
  ["", "Marc Lehmann"],
  ["", "Mark Miller"],
  ["", "Marketscore"],
  ["", "Marketwire L.P."],
  ["", "Mason Larobina"],
  ["", "Maxthon International Limited"],
  ["", "MAZ Systems Inc."],
  ["", "Mediatoolkit"],
  ["", "MegaIndex.ru"],
  ["", "Meizu Technology Co., Ltd."],
  ["", "Mesa Dynamics"],
  ["", "metauri.com"],
  ["", "Michael Dowling"],
  ["", "Michael Schoebel"],
  ["", "Microsoft Corporation"],
  ["", "Mikulas Patocka"],
  ["", "Mislav Marohnic"],
  ["", "Mixmax, Inc."],
  ["", "Moat, Inc."],
  ["", "Mobicip.com"],
  ["", "MobileIron"],
  ["", "Mojeek Ltd."],
  ["", "Monitor Backlinks Ltd."],
  ["", "Moonchild Productions"],
  ["", "MopoTab Inc"],
  ["", "Moreover Technologies, Inc"],
  ["", "Motorola"],
  ["", "Mozilla Foundation"],
  ["", "Myriad Group"],
  ["", "Nagios Enterprises, LLC."],
  ["", "National Institute of Information and Communications Technology, Japan"],
  ["", "National Library of Sweden"],
  ["", "Netcraft Ltd."],
  ["", "NetEase (Hangzhou) Network Co., Ltd."],
  ["", "netEstate GmbH"],
  ["", "Netscape"],
  ["", "NetSeer, Inc."],
  ["", "NetTrack"],
  ["", "News.me Inc"],
  ["", "NHN Corporation"],
  ["", "Nintendo"],
  ["", "No Limit Software"],
  ["", "Nokia"],
  ["", "Notify Ninja"],
  ["", "Novell"],
  ["", "NTENT"],
  ["", "NTT Resonant Inc."],
  ["", "Nuzzle Inc"],
  ["", "Obigo"],
  ["", "Oculus"],
  ["", "Omni Development Inc"],
  ["", "Online Media Group, Inc."],
  ["", "Opera Software ASA"],
  ["", "OPPO"],
  ["", "Oracle"],
  ["", "Orange S.A."],
  ["", "Oregan Networks Ltd"],
  ["", "otter-browser.org"],
  ["", "Panasonic"],
  ["", "Paper.li"],
  ["", "Paul Hammond"],
  ["", "Paypal"],
  ["", "pdrlabs.net"],
  ["", "phantomjs.org"],
  ["", "photonproject.net"],
  ["", "PingAdmin.ru"],
  ["", "Pingdom AB."],
  ["", "Pivotal Labs"],
  ["", "PlantRob"],
  ["", "Poco Systems Inc."],
  ["", "Polychrome Ltd"],
  ["", "Postbox, Inc."],
  ["", "Postman, Inc."],
  ["", "POTI Inc"],
  ["", "pr-cy.ru"],
  ["", "prlog.ru"],
  ["", "publiclibraryarchive.org"],
  ["", "Python Software Foundation"],
  ["", "Qihoo 360 Technology Co. Ltd."],
  ["", "Qualidator.com"],
  ["", "Quora, Inc."],
  ["", "QWANT SAS"],
  ["", "Radical Software Ltd"],
  ["", "rambler.ru"],
  ["", "rankflex.com"],
  ["", "Raven Internet Marketing Tools"],
  ["", "Raynette"],
  ["", "Read It Later, Inc"],
  ["", "RebelMouse"],
  ["", "Research and Development Unit for English Studies, Birmingham City University"],
  ["", "Research In Motion Limited"],
  ["", "Richard Trautvetter"],
  ["", "riddler.io"],
  ["", "Riser Apps LLC"],
  ["", "Ritlabs SRL."],
  ["", "Roku, Inc."],
  ["", "Rostelecom"],
  ["", "RostPay Ltd"],
  ["", "RuanMei.com"],
  ["", "Ryan Parman, Geoffrey Sneddon, Ryan McCue and contributors"],
  ["", "Ryte GmbH"],
  ["", "SafeDNS Inc"],
  ["", "Sakamoto Hironori"],
  ["", "Salesforce.com, Inc."],
  ["", "Samsung"],
  ["", "Scrapinghub Limited"],
  ["", "scrapy.org"],
  ["", "Searchturbo Ltd"],
  ["", "Semantic Dimension"],
  ["", "semantic-visions.com"],
  ["", "semantissimo.de"],
  ["", "semasio.com"],
  ["", "SEMrush"],
  ["", "SEO Cube S.r.l."],
  ["", "SEO Scanners"],
  ["", "SEO Site Checkup LLC"],
  ["", "seobility GmbH"],
  ["", "seodiver.com"],
  ["", "SEOmoz"],
  ["", "SEOmoz, Inc."],
  ["", "SERAPHIC Information Technology (Shanghai) Co., Ltd."],
  ["", "serpstatbot.com"],
  ["", "Seznam.cz, a.s."],
  ["", "Shilyaev Egor"],
  ["", "ShrinkTheWeb"],
  ["", "Sien"],
  ["", "SimilarTech Ltd."],
  ["", "Sina Corporation"],
  ["", "SISTRIX GmbH"],
  ["", "siteexplorer.info"],
  ["", "Siteimprove.com"],
  ["", "slack.com"],
  ["", "Snap Inc."],
  ["", "Socialrank.io"],
  ["", "Software in the Public Interest, Inc."],
  ["", "Sogou Inc"],
  ["", "Sohu.com Inc."],
  ["", "Sony"],
  ["", "SonyEricsson"],
  ["", "Soren Stoutner"],
  ["", "Sparrow SARL"],
  ["", "SpeedCurve"],
  ["", "Spotify AB"],
  ["", "SPRINKLR INC."],
  ["", "spyonweb.com"],
  ["", "Square, Inc."],
  ["", "SRWare"],
  ["", "Stanley Lim"],
  ["", "StatusCake"],
  ["", "Stefan Burstroem"],
  ["", "Stefano Alimonti"],
  ["", "Stephan Schmitz"],
  ["", "StumbleUpon, Inc."],
  ["", "superbird-browser.com"],
  ["", "Sur.ly"],
  ["", "Syllable Project"],
  ["", "Synacor, Inc."],
  ["", "Tapbots, LLC"],
  ["", "Taringa.net"],
  ["", "Tassaris"],
  ["", "team Haxx"],
  ["", "Tencent Ltd."],
  ["", "Tenta LLC"],
  ["", "Tesla Motors"],
  ["", "The Apache Software Foundation"],
  ["", "The British Legal Deposit Libraries"],
  ["", "the Dillo Project"],
  ["", "The Document Foundation"],
  ["", "the friendica project"],
  ["", "The GNOME Project"],
  ["", "The Old Reader"],
  ["", "the PHP Group"],
  ["", "The Rocket Science Group"],
  ["", "TheWorld.cn"],
  ["", "ThingLink Oy"],
  ["", "Thomas Dickey"],
  ["", "Thomas Schulte"],
  ["", "thumbnail.ws"],
  ["", "Tiscali"],
  ["", "Tobit Software AG"],
  ["", "Todd Ditchendorf"],
  ["", "Torsten Rueckert Internetdienstleistungen"],
  ["", "Toutiao"],
  ["", "Traackr Inc"],
  ["", "Tracemyfile Ltd."],
  ["", "Traffic Names Ltd"],
  ["", "trendiction.de"],
  ["", "Tumblr, Inc."],
  ["", "Turkcell"],
  ["", "Turnitin LLC"],
  ["", "Twingly AB"],
  ["", "Twitter"],
  ["", "ubermetrics-technologies.com"],
  ["", "UCWeb Inc."],
  ["", "Unity Technologies"],
  ["", "Uptime.com"],
  ["", "Valve Corporation"],
  ["", "Vebidoo.de"],
  ["", "Verisign"],
  ["", "VideoLAN non-profit organization"],
  ["", "Viderem AB"],
  ["", "visionmedia"],
  ["", "Vivaldi Technologies"],
  ["", "Vivo Global"],
  ["", "vk.com"],
  ["", "VSI innovation"],
  ["", "W3C"],
  ["", "Web CEO Limited"],
  ["", "Web Design Group"],
  ["", "webglance.com"],
  ["", "Webhose.io"],
  ["", "WebMeUp"],
  ["", "WeSEE Ltd"],
  ["", "WhiteHat Security"],
  ["", "wise-guys.nl"],
  ["", "wkhtmltopdf.org"],
  ["", "wmtips.com"],
  ["", "woorank.com"],
  ["", "wordpress.org"],
  ["", "www.acoobrowser.com"],
  ["", "www.freewebmonitoring.com"],
  ["", "www.newsblur.com"],
  ["", "www.phpclasses.org"],
  ["", "www.vbseo.com"],
  ["", "www.waterfoxproject.org"],
  ["", "Xavier Grangier"],
  ["", "Xavier Roche"],
  ["", "Xiaomi Tech"],
  ["", "Xovi GmbH"],
  ["", "Yahoo! Inc."],
  ["", "Yahoo!JAPAN"],
  ["", "Yandex LLC"],
  ["", "Yisou.com"],
  ["yoozBot", "yooz.ir"],
  ["JUZI Browser", "ZaoJianZhen"],
  ["Zend_Http_Client", "Zend Technologies Ltd."],
  ["Swing", "Zoom Internet Co., Ltd"],
  ["ZumBot", "ZUMinternet Corp"],
  ["Zvu", "zvu.com"],
]);
module.exports = DEVELOPERS;
